name: kalkulator
description: Kalkulator Pintar dengan fitur lengkap dan mode ilmiah.
version: 1.1.0+2
publish_to: 'none'

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  math_expressions: ^2.4.0
  shared_preferences: ^2.2.0
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/logo-kalkulator.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/icon/logo-kalkulator.png
    - assets/sounds/click.mp3
